### ISSUE TITLE
models/trakpak3_guard/spl/ends/pointed_0fw.vvd Causing compile issue

### ISSUE THREAD

**Issue by joeconqueror** [MagnumMacKivler/trakpak3#2]
Encountered this bug when compiling map with the pointed bridge guard ends. Similar issue brought up by Union as well.
  -19.57679Unable to load vertex data "models/trakpak3_guard/spl/ends/pointed_0fw.vvd"

**Comment by MagnumMacKivler** [comment]
Problem was an internal issue, fixed by recompiling.
![Imgur](https://i.imgur.com/wQvnwtF.png)
