### ISSUE TITLE
I was wondering if you could add more railroad crossings.

### ISSUE THREAD

**Issue by Fmlt2** [MagnumMacKivler/trakpak3#6]
Like a non gated crossing, more/different styles of the cross buck, like a cross buck with the X and the yield/stop is lower. Also can you make a bigger hang over crossing and one with more lights on the over hang. Also can you make a hang over that has the gate on its own stand?

**Comment by MagnumMacKivler** [comment]
This isn't really an issue, but I am going to add more crossing models in the future. I don't have many specific plans. In any case they are not a priority for now.
